# Generated by Django 4.2.6 on 2024-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('A', 'Accessories'), ('E', 'Electronics'), ('W', 'Watches'), ('H', 'Headphones'), ('C', 'Camera'), ('T', 'Television')], max_length=2),
        ),
    ]
